# Generated by Django 2.2 on 2020-02-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=500, verbose_name='视频地址'),
        ),
    ]
